.gitignore
.gitmodules
gdp-src-build/conf/bblayers.conf

1 part to test workflow
this can be independently merged

ocf demo /  Sandbox/pcoval/for/qemux86 64

---

init.sh

The submodule array in init.sh was a hardcoded array, which meant
it would require updating to reflect +- changes to .gitmodules.
This change should lower that maintenance overhead.

Switch submodule array in init.sh from a static array

---

gdp-src-build/conf/templates/dragonboard-410c.local.conf
init.sh

Require users to pass 'accept-eula' arg when initialising
build environment for dragonboard-410c

Add DragonBoard-410c EULA acceptance to init.sh

---

init.sh

[GDP-319] Allow the user to override the QEMU only option
for builds from master

Add force option to init script

---

.gitmodules

meta-ivi 9.0 branch has been updated to hotfix issues fetching
upstream dlt-daemon + node-startup-controller refs. Also switch
submodule to github.

meta-ivi: git repo fix for dlt-daemon + node-startup-controller

---

init.sh

The update to meta-raspberry brings in linux-raspberrypi
kernel 4.4.13, which includes various improvements to the vc4
drm driver support.
meta-raspberrypi:
2745399 gstreamer1.0-omx-1.2.0: Add patches and bbappend for 1.2.0 separately
3fb0a19 sdcard_image-rpi.bbclass: Add the vardepexcludes
6564e12 sdcard_image-rpi.bbclass: Exclude DATETIME from task stamp
101e8ab linux-raspberrypi_4.4: Upgrade to 4.4.13
10691ae firmware: Upgrade to 20160622
5cac5e6 userland: Upgrade to latest tip
43ecd9a sdcard_image-rpi: Always install dtb files
fe92cc7 rpi-mkimage: Remove unused recipe
d49bd07 u-boot: Use mainline u-boot recipe from oe-core
b34b4fe linux-raspberrypi: rpi-mkimage is no longer needed
5f12d84 packagegroup-rpi-test: Fix COPYING md5sum
f38938f linux-raspberrypi: Fix v4.1 with GCC6
4fb1a15 …

Update to meta-raspberrypi & raspberrypi2 supported to init.sh

---

gdp-src-build/conf/templates/porter.local.conf
gdp-src-build/conf/templates/renesas.local.inc
gdp-src-build/conf/templates/silk.local.conf
init.sh

Upgrade to meta-renesas YP 2.1 release.
Enable porter/silk board support for GDP Master
branch in init.sh again.

renesas: add renesas r-car gen 2 support for GDP11

---

init.sh

zsh will give cryptic error message
init.sh:13: unknown file attribute
better make a good error message if developer forgot to switch shell.

Add error message if mistakingly sourced from non bash (e.g zsh)

---

.gitignore

[GDP-449] toaster files are currently reported as untracked.
This change rectifies that problem.

Add toaster files to .gitignore

---

.gitmodules

New version of meta-rust is required for building
RVI SOTA Client.
[GDP-517] rvi-sota-client-git-r0 compiling failed
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

meta-rust: Update meta-rust

---

gdp-src-build/conf/templates/local.inc

Remove rpm package format support and only support ipk package format.
Signed-off-by: Changhyeok Bae changhyeok.bae@gmail.com

local.inc: Support only ipk package format

---

.gitignore
gdp-src-build/conf/templates/bblayers.inc

When developers run "source init.sh [device]", local.conf.[device] file
is copied from templates' to local.conf. So Before running the script,
developers change the local.conf file, the changed line in local.conf
is lost. To prevent this situation, this idea is suggested.
Developers can create gdp-local.conf in gdp-src-build directory and
add some changes in gdp-local.conf instead of local.conf.
hen changes are applied in GDP build.
[GDP-227] Improve single branch of genivi-dev-platform
Signed-off-by: Changhyeok Bae changhyeok.bae@gmail.com

bblayers.inc: Add developer.conf

---

.gitmodules
gdp-src-build/conf/templates/bblayers.inc

Add the meta-browser layer as a submodule, and add it to bblayers.conf together with meta-gnome, which is required because of chromium dependencies.
These changes need to be combined with this PR for meta-genivi-dev: GENIVI/meta-genivi-dev#53
Chromium would not be built by default yet, this is required to add it to the image:
```
IMAGE_INSTALL_append = " chromium-wayland"

chromium: Add meta-browser submodule

---

gdp-src-build/conf/templates/local.inc

[GDP-546] Drop Faytech support
Dropping Faytech monitor support since they've been known to cause
various problems and therefore make maintenance hard. List of currently
supported peripherals can be found at:
https://at.projects.genivi.org/wiki/display/GDP/GDP+and+peripherals

Drop Faytech support

---

.gitmodules
gdp-src-build/conf/templates/bblayers.inc

This is following instructions given at:
https://github.com/GENIVI/genivi-dev-platform/pull/58
One merged please merge:
https://github.com/GENIVI/meta-genivi-dev/pull/63

 meta-iot-web: Add new layer for iotivity-node support #58 (reopen)

---

git-submodule-bump

Add a shell script that makes it easy to bump submodules. The script
create (most of) the commit message for you. You still need to provide the
short log but script takes care of prefix for you. Here is an example run:
---------
$ ./git-submodule-bump "Bump to latest git master"
[wip/subm-update-commit bfff560] meta-ivi: Bump to latest git master
1 file changed, 1 insertion(+), 1 deletion(-)
---------
Signed-off-by: Zeeshan Ali <zeeshan.ali@pelagicore.com>

git-submodule-bump: Add helper for submodule bumps

---

git-submodule-bump

The merge commit deteriorates readability in commit log.
So remove merge commit when the commit log is created by
git-submodule-bump.

git-submodule-bump: Add no-merges option

---

gdp-src-build/conf/templates/koelsch.bblayers.conf
gdp-src-build/conf/templates/koelsch.local.conf
init.sh

Builds for Renesas Koelsch development board have previously been done
by building for the Porter board instead, and init.sh did not support
koelsch as a choice.  Added separate config files and koelsch as
unofficially supported.

Add (unofficial) Koelsch board support

---

git-submodule-bump

In shell script, exit status should be between 0 and 255.
0 is success number and others are failure number.

git-submodule-bump: Change exit number

---

README.md

As requested by @gunnarx I have gone ahead and created this PR to add the recently merged Renesas R-Car (Gen 3) M3 Starter Kit board to the readme. meta-genivi-dev PR #75 does the same for that layer. I have not added a m-g-d SHA update to this commit to make it easier to merge.

readme: add Renesas R-Car (Gen 3) M3 Starter Kit board

---

gdp-src-build/conf/templates/r-car-m3-starter-kit.local.conf

Typically the Renesas click-through licensed Evaluation
gfx and mmp packages will be used with the R-Car Gen 3
Starter Kit boards. Doing so requires a modification
to the DISTRO_FEATURES. Make that change the default
in the local.conf template for the board.
Fixes Jira issue GDP-583.
Signed-off-by: Stephen Lawrence <stephen.lawrence@renesas.com>

Fix JIRA GDP-583 with R-Car M3 Starter Kit build using click-through gfx/mmp pkgs on Go.CD

---

gdp-src-build/conf/templates/renesas-rcar-gen3.local.inc

Update the R-Car Gen 3 support to Genivi 12/YP 2.2 (Morty).
Support for Genivi 12 in the Yocto BSP is based on YBSP v2.17.
v2.17 requires an updated gfx and mmp [click through download
package](https://www.renesas.com/en-us/solutions/automotive/rcar-demoboard.html).
Tested on M3 Starter Kit.
[GDP-550] Upgrade GDP Master to yocto 2.2 (morty)

Update R-Car Gen 3 to Genivi 12/YP 2.2 (Morty)

---

gdp-src-build/conf/templates/dragonboard-410c.local.conf

meta-ivi: master branch (12.0.0 tag)
poky: Upgrade to morty branch used in baseline 12.0.0
meta-openembedded: Upgrade to morty branch used in baseline 12.0.0
dragonboard-410c.local.conf
- aarch64 target for qemu is now applied in meta-ivi. Therefore remove it from dragonboard local conf

Upgrade to GENIVI Baseline 12.0.0 (NOSTROMO)

---

init.sh

Some people run zsh instead of bash, it's nice to have the script compatible
with both. Thes patch makes this possible and at the same time it makes all
used variables local within a function so they don't leak out without the
need of deleting them at the end.

init.sh: Make script compatible with zsh

---

gdp-src-build/conf/templates/renesas-rcar-gen3.local.inc

Update the renesas-rcar-gen3 submodule to fix JIRA ticket GDP-590
(qtbase do_configure build failure: OpenGL ES 2.0 disabled) [1].
To enable the fix add packagegroup-graphics-libegl to IMAGE_INSTALL.
[1] https://at.projects.genivi.org/jira/browse/GDP-590

renesas-rcar-gen3: Update to 4ebc763eb4 to fix GDP-590

---

git-submodule-bump

Partial improvement of git-submodule-bump and fix bug [GDP-638](https://at.projects.genivi.org/jira/browse/GDP-638).   Ultimately I'd like to give the changed submodule as argument, but not the time for fixing this now.

Remove Bashisms and improve git-submodule-bump

---

meta-genivi-dev/meta-genivi-dev/recipes-multimedia/pulseaudio/pulseaudio/am_poc.pa

Add load module lines to the configuration for pulseaudio that enables
the a2dp protocol.

pulseaudio: Load modules w/ a2dp protocol support

---

meta-genivi-dev/meta-genivi-dev/recipes-extended/chromium/chromium-wayland_%.bbappend
meta-genivi-dev/meta-genivi-dev/recipes-graphics/wayland/wayland-ivi-extension/0001-ilmControl-fix-memory-corruption-at-input-listener.patch
meta-genivi-dev/meta-genivi-dev/recipes-graphics/wayland/wayland-ivi-extension_%.bbappend

This patch set adds the multi-seat implementation to the chromium build in GENIVI.
The multi-seat patch has already been modified to pull the ozone-wayland fork that implements [multi-seat](https://github.com/jaragunde/ozone-wayland/tree/wip/multi-seat).
Unfortunately, we must wait to merge this PR. It includes a downstream patch for wayland-ivi-extension to fix GDP-616. The patch must be modified when a new bugfix release of that software happens.

Chromium multi-seat implementation

---

init.sh

Make the init.sh script return non-zero when an unsupported target is
given as argument. This fixes bug GDP-581.
[GDP-581] init.sh has successful return code even for unknown target

[GDP-581] init.sh: Return 1 when provided unsupported target

---

meta-genivi-dev/meta-genivi-dev/recipes-extended/ivi-logging/ivi-logging.bb

These are moved over from a previous PR on meta-ivi as we agreed it's not the right place for it at the time being. Reference: https://github.com/GENIVI/meta-ivi/pull/43
I'm uncertain of the placement of the recipes, please check if you are ok with it.

ivi-logging: Adds initial ivi-logging version

---

scripts/ci-build.sh

ci-build.sh: Create a file list for the image
For some situations it's useful to just quickly confirm if a file exists
in the system. If publishing a small text file containing a file
manifest then there's no need to download a large image or tarball to do
such checks.
ci-build.sh will now do that by default and it's possible to turn off
by env var CREATE_ROOTFS_FILE_LIST = false
Note: It was simply written for .tar.gz rootfs packages now - so this
might need tweaking if we don't include a tarball in IMAGE_FSTYPES in
some cases.

Create a file list for the image (ci-build script)

---

meta-genivi-dev/meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb

Bumps gdp-new-hmi to the latest version where the browser button on the
home screen launches the correct application as excpected.
[GDP-683] Main window the browser icon it does not work

GDP-HMI: Fix browser button on home screen

---

meta-genivi-dev/poky/meta/recipes-graphics/wayland/weston/weston.ini

The keyboard layout is set to German in weston.ini. This change removes
that setting making weston load the default layout i.e. English.
[GDP-574] GDP has German keyboard layout

Set keyboard layout to default (English)

---

meta-genivi-dev/poky/meta/recipes-graphics/wayland/weston/weston.service

This is a workaround to solve the issue with weston-launch some times
failing to start.
[GDP-607] Sometimes Weston 1.11 fails to start

weston-service: Restart on crash

---

init.sh

Bitbake (python in fact) requires a terminal locale that supports UTF-8. Most of the time users will have that but not always.  Also in some simplified environments like CI-builds it might be missing.  For simplicity's sake I figured we can have init.sh set a locale like English/US/UTF-8 in case it needs to be done.

init.sh: Add a simple help to avoid locale errors

---

meta-genivi-dev/meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/bluetoothpairingapp/com.genivi.gdp.bluetoothPairingApp.desktop
meta-genivi-dev/meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/bluetoothpairingapp_git.bb
meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/packagegroups/packagegroup-gdp-hmi.bb
meta-genivi-dev/meta-genivi-dev/recipes-extended/blueconnect/blueconnect_git.bb

*Note:* This currently pulls from git://github.com/dunderroffe/bluetoothpairingapp (there are no genivi repo yet) which has to be changed before merging. 
Add BluetoothPairingApp and the required depenency blueConnect.

Add BluetoothPairingApp

---

meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/packagegroups/packagegroup-gdp-dev.bb
meta-genivi-dev/meta-genivi-dev/recipes-extended/cannelloni/cannelloni.bb
meta-genivi-dev/meta-genivi-dev/recipes-extended/cannelloni/files/launch_cannelloni.service
meta-genivi-dev/meta-genivi-dev/recipes-extended/cannelloni/files/launch_cannelloni.sh

GDP-710 :
Write a Yocto recipe for Cannelloni in order to compile and install it with the rest of GDP. Also write a systemd service description to start the server at boot time (for now, this is probably subject to change).
Added recipe for cannelloni and lanch cannelloni systemd service. For now lanching script does nothing. 
Task does not define where this recipe should be added. For now it has been added to:
meta-genivi-dev/meta-genivi-dev/recipes-extended/

Integrate Cannelloni with the Yocto build system

---

meta-genivi-dev/poky/meta/recipes-core/packagegroups/nativesdk-packagegroup-sdk-host.bbappend

The dependency chain for the nativesdk-dnf is currently broken. DNF is currently not used
and/or supported by the genivi-dev-platform anyways, so removing the dependency.
Signed-off-by: Oscar Andreasson <oscar.andreasson@pelagicore.com>

nativesdk: Remove dnf support

---

meta-genivi-dev/meta-genivi-dev/recipes-extended/cannelloni/cannelloni.bb

WARNING: cannelloni-1.0-r0 do_populate_lic: Could not copy license file
...........
[Errno 2] No such file or directory:
'.../gdp/poky/meta/files/common-licenses/GPLv2'

cannelloni: Fix license check warning

---

meta-genivi-dev/meta-genivi-dev/recipes-extended/dbus-c++/dbus-c++-native.bb
meta-genivi-dev/meta-genivi-dev/recipes-extended/dbus-c++/dbus-c++.inc
meta-genivi-dev/meta-genivi-dev/recipes-extended/dbus-c++/dbus-c++/0001-Pass-correct-type-of-argument.patch

On my Fedora 26 host, these patches are needed to get GDP build successfully.

Fix build against gcc 7.1.1

---

gdp-src-build/conf/layer.conf
meta-genivi-dev/meta-erlang/conf/layer.conf
meta-genivi-dev/meta-genivi-dev/conf/layer.conf
meta-genivi-dev/meta-ivi/conf/layer.conf
meta-genivi-dev/meta-qt5/conf/layer.conf
meta-genivi-dev/meta-raspberrypi/conf/layer.conf
meta-genivi-dev/meta-rvi/conf/layer.conf
meta-genivi-dev/poky/conf/layer.conf

Rename layer name from "genividev" to "genivi-dev"
to be used in collections.
This way this layer can be optionally and dynamicaly overloaded by sub layer,
using this scriplet:
BBFILES += "${@' '.join('${LAYERDIR}/meta-%s/recipes*/*/*.bb' % layer \
for layer in BBFILE_COLLECTIONS.split())}"
This is meta-ocf-automotive strategy to support specific features
for diferents distros, for more details track:
https://wiki.iotivity.org/automotive
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

conf: Align layer name to directory name

---

gdp-src-build/conf/templates/local.inc

New attempt.  Refer to #136 for more details.
The difference is this branches meta-erlang from the version we had, and does therefore not update to the latest tip of master.  Thus, the OTP version is held back at 18.2.3 which is what we had.  Hopefully this compiles.

Erlang hotfix keeping version 18.2.3

---

meta-genivi-dev/poky/meta/recipes-core/packagegroups/nativesdk-packagegroup-sdk-host.bbappend

meta-flatpak is updated to fix dnf parsing problem.
So nativesdk-packagegroup-sdk-host.bbappend is not required anymore.

Remove nativesdk-packagegroup-sdk-host.bbappend

---

.gitmodules
gdp-src-build/conf/templates/r-car-h3-starter-kit.bblayers.conf
gdp-src-build/conf/templates/r-car-h3-starter-kit.local.conf
gdp-src-build/conf/templates/r-car-m3-starter-kit.bblayers.conf
gdp-src-build/conf/templates/renesas-rcar-gen3.bblayers.inc
init.sh

Add support for the [R-Car H3 Starter Kit Premier board](http://www.elinux.org/R-Car/Boards/H3SK) to the GDP setup scripting.
This was developed on top of PR #140 (not yet merged) so includes commit 35979c1 as its the only way for github to allow me to create the PR.
[GDP-746] Add Renesas R-Car H3 Starter Kit support to setup scripting

Add support for Renesas R-Car H3 Starter Kit board

---

meta-genivi-dev/meta-qt5/recipes-qt/qt5/qtwayland_%.bbappend

**Usage Note**
When building GDP-13 for R-Car Gen 3 please use the YBSP v2.23 (Weston 2.0) gfx driver package download from [here](https://www.renesas.com/en-us/solutions/automotive/rcar-demoboard-2.html). If you use the YBSP v2.19 package used with GDP-12 the screen image will be inverted.
**Description**
Fix qtwayland configure error that results in the wayland_egl plug-in
not being built and therefore not shipped in the rootfs. The missing
files result in the gdp hmi launcher failing to start with the systemd
journal error message:
Failed to load client buffer integration: wayland-egl
[GDP-752] QtWayland configure failure for wayland_egl plug-in
[GDP-753] GDP HMI fails to launch on R-Car M3 Starter Kit
Signed-off-by: Stephen Lawrence <stephen.lawrence@renesas.com>

qtwayland: fix R-Car M3 Starter Kit gdp hmi startup issue

---

meta-genivi-dev/meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/connectedhome.bb
meta-genivi-dev/meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/connectedhome/com.genivi.gdp.connectedhome.desktop
meta-genivi-dev/meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb
meta-genivi-dev/meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/hvac.bb
meta-genivi-dev/meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/hvac/com.genivi.gdp.hvac.desktop
meta-genivi-dev/meta-genivi-dev/recipes-extended/browser-poc/browser-poc-git/browser.desktop
meta-genivi-dev/meta-genivi-dev/recipes-extended/browser-poc/browser-poc-git/browser.service
meta-genivi-dev/meta-genivi-dev/recipes-extended/browser-poc/browser-poc-git/demoui.service
meta-genivi-dev/meta-genivi-dev/recipes-extended/browser-poc/browser-poc_git.bb
meta-genivi-dev/meta-genivi-dev/recipes-multimedia/audiomanager/audiomanager-demo/AudioManager_Monitor.desktop
meta-genivi-dev/meta-genivi-dev/recipes-multimedia/audiomanager/gdp-audiomanager-monitor.bb
meta-genivi-dev/meta-genivi-dev/recipes-multimedia/audiomanager/gdp-audiomanager-monitor/AudioManager_Monitor.desktop
meta-genivi-dev/meta-genivi-dev/recipes-multimedia/audiomanager/gdp-audiomanager-monitor/AudioManager_Monitor.service
meta-genivi-dev/meta-ivi/recipes-graphics/wayland/wayland-ivi-extension/EGLWLInputEventExample.desktop
meta-genivi-dev/meta-ivi/recipes-graphics/wayland/wayland-ivi-extension/EGLWLInputEventExample.service
meta-genivi-dev/meta-ivi/recipes-graphics/wayland/wayland-ivi-extension/EGLWLMockNavigation.desktop
meta-genivi-dev/meta-ivi/recipes-graphics/wayland/wayland-ivi-extension/EGLWLMockNavigation.service
meta-genivi-dev/meta-ivi/recipes-graphics/wayland/wayland-ivi-extension_%.bbappend

Move all desktop files from application repositories to the genivi-dev-platform yocto layer.
This pull-request also makes the "Connected Home" app run in bubblewrap.

Move desktopfiles to yocto repo and start bwrapping apps

---

README.md
meta-genivi-dev/README.md

Now Renesas R-Car H3 Starter Kit has been added to the GDP automated
setup system add details for it to the readme files.
At the same time take the opportunity to bring R-Car information in
the readme files up to date.
Signed-off-by: Stephen Lawrence <stephen.lawrence@renesas.com>

readme: add Renesas R-Car H3 Starter Kit, update R-Car text

---

meta-genivi-dev/meta-genivi-dev/recipes-devtools/python/python-pyqt_5.3.1.bb

Other layers (poky, meta-openembedded) use the $SOURCEFORGE_MIRROR
variable (somewhat consistently) to indicate the preferred mirror when
defining SRC_URI.
This component was hardcoded to https://download.sourceforge.net, but it
should respect the SOURCEFORGE_MIRROR variable instead.
This was found when sourceforge was down a few weeks ago, although
switching mirror did not help much at that time, since basically all
mirrors seemed to have been taken down temporarily.

python-pyqt_5.3.1: Use ${SOURCEFORGE_MIRROR}

---

scripts/ci-build.sh

Enables building a version of GDP parent project, with a particular layer exchanged for a different version.
Launching various on-demand build checks and other CI scenarios is easily 
done by setting new environment variables, per layer.
There are a few more commits here, with cleanup etc.

CI: enable override of one particular layer version

---

scripts/ci-build.sh

Before:  tried to move images/\<stuff\> but in the yocto tmp dir images are stored in images/\<targetname\>/stuff
Now: Fixed in the way you can see with a * wildcard for target
Also, more image type patterns added.
Ultimately, many builds also need adjustment so they don't build unnecessary image types, but that's independent of this.

ci-build: Fix bug moving staging/images + release dir

---

scripts/update_baseline_dependency_layers.sh

When meta-ivi updates, it defines the compatible commits/versions of
dependent layers such as poky and meta-openembedded in its README.
After updating meta-ivi, running this script will update the layers in
GDP to the versions proposed by the baseline.  Sometimes we may choose
to deviate from it, but it is a starting point that is likely to be
compatible.

Add script to update meta-ivi's dependencies

---

scripts/ci-build.sh

Additional environment variables allow to wipe tmp/ downloads/ and
sstate-cache/, or to keep and reuse them.  The default is (as before) to
always wipe them before building.

ci-build: Options to not wipe TMP/DL/SSTATE between builds

---

scripts/ci-build.sh

The ci-build script would clobber the user's user.name and user.email
settings in git, because that makes no difference in a throw-away CI
environment.  It is required (in some cases, such as when git is used as
patch tool) that there is SOME setting for user/email in the CI build.
But since ci-build.sh could be useful to run also locally, the original
settings must be restored when the script ends.

ci-build: Restore user.name/email

---

scripts/ci-build.sh

Adding environment variables to define MIRRORS and PREMIRRORS variables. Only one URL for each is supported here.  PREMIRROR is by default empty, and MIRROR is by default set to a GENIVI hosted mirror.  (MIRRORS is used by Yocto as a fallback if all other source fetch options failed)
For PREMIRRORS it is normally more convenient to use the own-mirrors BB class, but since MIRRORS need to be explicitly defined, I used the same format for PREMIRRORS.
It's quite arbitrary but I chose to apply the PREMIRROR definition first (prepend) and MIRROR definition last (append), in case there were any settings already.  Seems somewhat logical that this is the desired
behavior.
NOTE that keeping the GENIVI mirror automatically up to date is not yet implemented, but the content is up to date with 13.0 …

ci-build.sh: Add GENIVI MIRROR + PREMIRROR option

---

meta-genivi-dev/meta-genivi-dev/recipes-extended/chromium/chromium-wayland_%.bbappend

Occasionally we had a compile error where the header file ilm_common.h
was not found during compilation of chromium-wayland.  This header comes
from wayland-ivi-extension.  The error seems to have gone away (or is
depending on some random build order?).  In any case I can't imagine
anything else than that the version of chromium-wayland we build should
DEPEND on wayland-ivi-extension.

chromium-wayland: Depend on wayland-ivi-extension

---

gdp-src-build/conf/templates/bblayers.inc

Fetching meta-erlang is fixed and pull request is sent.
(https://github.com/GENIVI/meta-genivi-dev/pull/97)

fix build error: meta-erlang

---

gdp-src-build/conf/templates/bblayers.inc
meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/packagegroups/packagegroup-gdp-dev.bb
meta-genivi-dev/meta-openembedded/meta-oe/conf/layer.conf
meta-genivi-dev/meta-openembedded/meta-oe/recipes-support/udisks2/files/org.freedesktop.UDisks2.conf
meta-genivi-dev/meta-openembedded/meta-oe/recipes-support/udisks2/files/udisks2-disk-manager.service
meta-genivi-dev/meta-openembedded/meta-oe/recipes-support/udisks2/files/udisks2-disk-manager.sh
meta-genivi-dev/meta-openembedded/meta-oe/recipes-support/udisks2/udisks2_%.bbappend

This pull-request will add udisks2 to the GDP image, along with a example service to auto-mount storage devices on hot-plug events.
Note that the D-Bus policy is very permissive.
I am a bit unsure if `packagegroup-gdp-dev"  was the correct location to these packages. If there is a more appropriate group that we should add these please let me know.

[GDP-252] Add support for udisks2 to the GDP image

---

README.md

Current release is actually GDP 13 and the download page has been renamed so update the link.
Signed-off-by: Mirza Krak <mirza.krak@endian.se>

README: update current release and fix broken link

---

scripts/ci-build.sh

@gunnarx this contains two work streams but as these need to be merged into the rocko working branch I have not split them into separate PRs. Felt like it will just add a bunch of work to CI that is not needed. Rocko should be built with both anyway.
The two streams are:
1. Update to meta-ivi release 14.0.0 layer commits.
Whilst doing the Yocto BSP v3.7.0 update I noticed that GDP was still using the old P-0.1 release layers specified in the meta-ivi README.md. So there are commits to bring meta-oe, poky and meta-gplv2 up to date.
2. Update R-Car Gen 3 support to Yocto BSP v3.7.0 ([GDP-789](https://at.projects.genivi.org/jira/browse/GDP-789))
Update the Renesas R-Car Gen 3 board support to use Yocto BSP v3.7.0.
I would really like to see the BSP v3.7.0 update pulled into the rocko working …

rocko: Update meta-ivi layers. Update R-Car Gen 3 to Yocto BSP v3.7.0

---

meta-genivi-dev/meta-genivi-dev/recipes-core/systemd/systemd_%.bbappend

udisks2 depends on polkit which installs the same catalog as the systemd.bb does if **PACKAGECONFIG[polkit]** is enabled. 
Example, raspberry pi build:
```
02:39:24.505   file /usr/share/polkit-1/rules.d conflicts between attempted installs of systemd-1:234-r0.cortexa7hf_neon_vfpv4 and polkit-0.113-r0.cortexa7hf_neon_vfpv4
```
There seems to be two options: - keep polkit enabled for systemd but redefine the installation step to fix the conflict for the directory installation, or remove polkit feature in systemd build.
Disabling the feature will also configure systemd build with --disable-polkit.
What is it used for?    Polkit can be used to control which systemd services can be controlled
by regular users.  I am guessing  that feature is not required here and it seems more tailored for a …

[GDP-791] systemd: Configure without polkit (for now)

---

gdp-src-build/conf/templates/local.inc
gdp-src-build/conf/templates/renesas-rcar-gen3.local.inc

RPM was our primary package manager which means that the
do_rootfs would use dnf to install all the required packages.
Currently RPM has performance issues when running inside a
docker container, which our builds normally do on our build
servers but it is also quite common to run this on developer
machines as well.
The performance issues are rapported and fixed in upstream RPM,
https://bugzilla.redhat.com/show_bug.cgi?id=1537564.
But since we do not rely on using RPM we simply remove it instead
of trying to backport and maintain a patchset for a couple of
Yocto release. Currently only poky/master has the "fixed" RPM
package.
[GDP-793] rpm in docker is slowing down builds
Signed-off-by: Mirza Krak <mirza.krak@endian.se>

templates: local.inc: remove package_rpm

---

gdp-src-build/conf/templates/local.inc
meta-genivi-dev/meta-genivi-dev/lib/oeqa/runtime/cases/devpackages.py
meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/images/genivi-dev-platform.bb
meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/packagegroups/packagegroup-gdp-dev.bb
meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/packagegroups/packagegroup-gdp-gps.bb
meta-genivi-dev/meta-genivi-dev/recipes-extended/automotive-message-broker/automotive-message-broker_git.bb
meta-genivi-dev/meta-genivi-dev/recipes-navigation/positioning/positioning_git.bb
meta-genivi-dev/meta-openembedded/meta-oe/recipes-support/udisks2/files/udisks2-disk-manager.sh

Got rid of all "sneaky" dependencies on -dev packages polluting our target image.
Also added a test (TDD :)) to make sure that this does not sneak back in.
The last commit does not really have to do anything with GDP-787, but is more of a clean-up task which I did while I investigated all suspects.

GDP-787 - Remove dev files from target image

---

gdp-src-build/conf/templates/raspberrypi.local.inc
meta-genivi-dev/meta-rvi/recipes-connectivity/rvi/files/0001-rvi_ctl.template-get-rid-of-dependecy-on-install.patch
meta-genivi-dev/meta-rvi/recipes-connectivity/rvi/rvi_git.bbappend

Fixes issues found during rocko testing, https://at.projects.genivi.org/wiki/display/GDP/GDP+Testing

meta-raspberrypi: update to latest on rocko

---

scripts/ci-build.sh

Update the Renesas R-Car Gen 3 board support to use Yocto BSP v3.9.0 (GDP-800).
Successfully sanity tested on the R-Car M3 Starter Kit.

rocko: Update Renesas R-Car Gen 3 to Yocto BSP v3.9.0

---

gdp-src-build/conf/templates/qemux86-64.local.conf
meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/images/genivi-dev-platform.bb

First patch fixes an issue where disk could end up full when booting QEMU.
Second is a "stability improvement"

Qemu fixes

---

scripts/ci-build.sh

To save diskspace in build environment we'll make this the default. As
before, environment variables can be overridden. export RM_WORK=false
before running script if you want to keep those files.

ci-build: Use RM_WORK by default

---

meta-genivi-dev/meta-genivi-dev/recipes-extended/cannelloni/cannelloni.bb

The license file md5 checksum is specified in uppercase which can lead
to a build error when compared to a lowercase sum generated at runtime.
For example:
ERROR: cannelloni-1.0-r0 do_populate_lic: QA Issue: cannelloni: The LIC_FILES_CHKSUM does not match for file://gpl-2.0.txt;md5=B234EE4D69F5FCE4486A80FDAF4A4263
cannelloni: The new md5 checksum is b234ee4d69f5fce4486a80fdaf4a4263
To avoid such issues specify the checksum in lowercase.
The strange thing in my mind is why this has not been an error before as the checksum check in insane.bbclass appears to be case sensitive. I see the error in a build for H3 Starter Kit, but M3 Starter Kit is ok. I've posted a question about that to the YP mailing list.

cannelloni: fix license checksum

---

README.md
gdp-src-build/conf/templates/r-car-h3-salvator-x.local.conf
gdp-src-build/conf/templates/r-car-m3-salvator-x.local.conf
gdp-src-build/conf/templates/renesas-rcar-gen3.local.inc

- Enable USB 3.0 support in Salvator-X builds
- Reorder the lines in the local.conf templates so they follow that used in the Starter Kit templates and the sample local.confs in the Yocto BSP.
- add missing u-boot/IPL build options to H3 Salvator-X local.conf template.
- add the Salvator-X boards to the README.
Marked WIP as code is currently under testing.

[WIP] Update Renesas R-Car Salvator-X board template support

---

meta-genivi-dev/meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb

This commit:
https://github.com/GENIVI/genivi-dev-platform/commit/fa227829f1696775a02396eafb73db05748b4f1f
Accidently downgraded the GDP HMI to a revision that is
broken. Fix by updating to the latest known revision.
Signed-off-by: Mirza Krak <mirza.krak@northern.tech>

gdp-new-hmi: fix SRCREV

---

meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/images/genivi-dev-platform-core.bb

Just a minor PR to bump the PV set in the image recipe - to for mirzak to comment.  
Is this PV setting reused for other images that include core, and does it serve some useful purpose or not much...  Read commit comment for rationale also.  We could have a chat in person, if it's easier.

genivi-dev-platform-core: Set image PV to 14 on master branch
