LICENSE
Chose the MIT license.
Closes #4
=> Added License and Copyright info

.gitmodules, gdp-src-build/conf/bblayers.conf
[GDP-159] Add meta-rvi and meta-erlang for building
RVI (Remote Vehicle Interaction).
(From meta-rvi rev: de9d548fe35e2cee8688faaae910b4f6f7fea17e)
(From meta-erlang rev: 4d7eacc8e6593934ed5b0c8abc3d3e9dc339d849)
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
=> meta-rvi: Add layers for RVI

.gitignore, init.sh
After using one branch, bblayers.conf and local.conf is copying from
template directory. So Need not to add those configuration files
in commit.
[GDP-126] New repo/branch structure for GDP: analysis and proof of
concept (PoC)
=> Add bblayers.conf and local.conf in gitignore, and remove env check in init.sh

gdp-src-build/conf/templates/raspberrypi3.bblayers.conf, gdp-src-build/conf/templates/raspberrypi3.local.conf, init.sh
[GDP-128] GDP-ivi9 on RPi3
[GDP-218] GDP 10 port to RPi3: creation
=> Support raspberrypi3

gdp-src-build/conf/templates/raspberrypi2.local.conf
Only configuration difference of raspberrypi2 and raspberrypi3 is
MACHINE variable.
[GDP-248] Question about differences in local conf rpi2 / rpi3
=> raspberrypi2.local.conf: Use same configuration with rpi3

.gitmodules, gdp-src-build/conf/templates/dragonboard-410c.bblayers.conf, gdp-src-build/conf/templates/dragonboard-410c.local.conf, init.sh
Add meta-qcom layer
meta-genivi-dev
3691f06 README.md: Add dragonboard-410c machine
9d841d8 Fix broken resolution for dragonboard-410c
f973338 keyutils: Fix build error in arm 64bit
[GDP-226] Support qualcomm DragonBoard 410c
=> Support dragonboard-410c

README.md, gdp-src-build/conf/templates/local.inc, init.sh
[GDP-281] Upgrade GDP Master to baseline 11 (MIRANDA)
=> Upgrade GDP Master to baseline 11 (MIRANDA)

README.md
[GDP-301] The readme should only refer to boards supported
in the beta release
=> Update README.md for beta

init.sh
[GDP-266] Support Intel Minnowboard MAX in Master
meta-intel: upgrade to krogoth release
meta-genivi-dev: faytech patch for 4.4 kernel
init.sh: rework to add minnowboard as supported
=> minnowboard: Add minnowboard yocto2.1 support for GDP11

init.sh
=> init.sh: Support dragonboard-410c

init.sh
- Support Raspberry PI3
- Fix bluetooth launch problem in RPI3
=> Support Raspberry PI3

gdp-src-build/conf/templates/local.inc
meta-genivi-dev: Temporarily use audiomanager & audiomanagerplugins 7.0
meta-ivi: audiomanager: version up to 7.4
local.inc: set audiomanager/plugins preferred version to 7.0
=> Revert to temporarily using audiomanager7.0

.gitmodules, gdp-src-build/conf/templates/r-car-m3-starter-kit.bblayers.conf, gdp-src-build/conf/templates/r-car-m3-starter-kit.local.conf, gdp-src-build/conf/templates/renesas-rcar-gen3.local.inc, init.sh
- Add submodules for the Renesas R-Car Gen 3 (H3/M3) SoC Yocto BSP
- Add initialisation support for the Renesas R-Car M3 Starter Kit low cost board
=> Add Renesas R-Car Gen 3 board support

gdp-src-build/conf/templates/bblayers.inc, gdp-src-build/conf/templates/dragonboard-410c.bblayers.conf, gdp-src-build/conf/templates/minnowboard.local.conf, gdp-src-build/conf/templates/raspberrypi.local.inc
[GDP-550] Upgrade GDP Master to yocto 2.2 (morty)
=> Upgrade GDP Master to yocto 2.2 (morty)

scripts/ci-build.sh
This works well for me now on my fork.  I'm sure it will need updates but it would help if we can merge it to master quickly and have it available also for the standard CI.
=> Add script to help CI builds

init.sh
Not a really clean PR here since there might be somewhat unrelated changes.  I was going to push these directly in fact - but I'm concerned with one of the commits removal of official support targets might break a few builds that need the -force flag.  So I'll run it through the PR.
=> Various init.sh update

meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/images/genivi-dev-platform.bb, meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/packagegroups/packagegroup-gdp-vsi.bb, meta-genivi-dev/meta-genivi-dev/recipes-vsi/vehicle-signal-interface/vehicle-signal-interface_2.0.0.bb
Signed-off-by: Oscar Andreasson <oscar.andreasson@pelagicore.com>
=> Adding vehicle_signal_interface_2.0.0.bb

meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/images/genivi-dev-platform.bb, meta-genivi-dev/poky/meta/recipes-core/dbus/dbus_%.bbappend
Sorry for short comments - short on time.  Please see the 2 commits.
=> 2 sdk fixes

meta-genivi-dev/meta-ivi/recipes-multimedia/audiomanager/audiomanager/AudioManager_user.service, meta-genivi-dev/poky/meta/recipes-multimedia/pulseaudio/pulseaudio/am_poc.pa, meta-genivi-dev/poky/meta/recipes-multimedia/pulseaudio/pulseaudio/pulseaudio_user.service
This addresses some sound issues we're currently having with the platform. It's not everything but a start.
=> Fix audio issues

meta-genivi-dev/meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/hvac.bb
For some reason the installation of the imports and some other files was
deleted. Re-adding the installation of the files.
=> HVAC: Bugfix installation

meta-genivi-dev/meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/bluetoothpairingapp_git.bb
Signed-off-by: Oscar Andreasson <oscar.andreasson@pelagicore.com>
=> Fork bluetoothpairingapp to genivi namespace on github

meta-genivi-dev/meta-genivi-dev/recipes-extended/chromium/chromium-wayland_%.bbappend
Signed-off-by: Remigiusz Kołłątaj <remigiusz.kollataj@mobica.com>
=> Adding h3ulcb as a compatible machine for chromium-wayland

meta-genivi-dev/meta-genivi-dev/recipes-extended/chromium/chromium-wayland/dragonboard-410c/include.gypi, meta-genivi-dev/meta-genivi-dev/recipes-extended/chromium/chromium-wayland/dragonboard-410c/oe-defaults.gypi, meta-genivi-dev/meta-genivi-dev/recipes-extended/chromium/chromium-wayland_%.bbappend
We had this open before but closed again.  It's now up to date with master (pyro branch etc).
I'm placing it here for comparison with chromium_pyro.  Please feel free to review it for commit content/format. I suggest to not merge until testing is concluded however.
=> Dragonboard chromium pyro

gdp-src-build/conf/templates/bblayers.inc, gdp-src-build/conf/templates/local.inc, meta-genivi-dev/meta-genivi-dev/recipes-cdl/cdl-concept-demo/cdl-concept-demo.bb, meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/images/genivi-dev-platform.bb, meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/packagegroups/packagegroup-gdp-dev.bb, meta-genivi-dev/meta-genivi-dev/recipes-extended/genivi-browser-test-hmi-precompiled/genivi-browser-test-hmi-precompiled.bb, meta-genivi-dev/meta-genivi-dev/recipes-extended/minifi-cpp/files/0001-MINIFICPP-562-Fixed-thirdparty-uuid-include-path.patch, meta-genivi-dev/meta-genivi-dev/recipes-extended/minifi-cpp/files/0002-thirdparty-date-remove-usage-of-SYSTEM.patch, meta-genivi-dev/meta-genivi-dev/recipes-extended/minifi-cpp/files/minifi.service, meta-genivi-dev/meta-genivi-dev/recipes-extended/minifi-cpp/minifi-cpp_0.5.0.bb
Proof of Concept state and have not tested enabling all the extensions,
but the default and core components build and deploy properly.
Tested running the minifi controller target with:
/usr/bin/minifi.sh start
Signed-off-by: Mirza Krak <mirza.krak@northern.tech>
=> meta-genivi-dev: initial recipe for Apache MiNiFi

gdp-src-build/conf/templates/local.inc, gdp-src-build/conf/templates/minnowboard.local.conf, gdp-src-build/conf/templates/qemux86-64.local.conf, gdp-src-build/conf/templates/raspberrypi.local.inc, gdp-src-build/conf/templates/renesas-rcar-gen3.local.inc, meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/images/genivi-dev-platform.bb, meta-genivi-dev/meta-genivi-dev/wic/singlepart-noloader.wks
I have some more testing pending as the changes effect all supported boards, but wanted get a complete build test and acceptance test run on this.
=> GDP-810 - IMAGE_FSTYPES cleanup

gdp-src-build/conf/templates/bblayers.inc, meta-genivi-dev/meta-erlang/conf/layer.conf, meta-genivi-dev/meta-genivi-dev/conf/layer.conf, meta-genivi-dev/meta-genivi-dev/recipes-sota/genivi-swm/genivi-swm_git.bb, meta-genivi-dev/meta-intel-gdp/conf/layer.conf, meta-genivi-dev/meta-ivi/conf/layer.conf, meta-genivi-dev/meta-openembedded/meta-oe/conf/layer.conf, meta-genivi-dev/meta-openembedded/meta-oe/recipes-support/udisks2/udisks2_%.bbappend, meta-genivi-dev/meta-qt5/conf/layer.conf, meta-genivi-dev/meta-raspberrypi/conf/layer.conf, meta-genivi-dev/meta-renesas/meta-rcar-gen3/conf/layer.conf, meta-genivi-dev/meta-rvi/conf/layer.conf, meta-genivi-dev/meta-sdl/conf/layer.conf, meta-genivi-dev/meta-sdl/recipes-automotive/sdl-core/files/0001-a2dp_source_player_adapter-fix-API-reference-to-GetD.patch, meta-genivi-dev/meta-sdl/recipes-automotive/sdl-core/sdl-core_4.5.%.bbappend, meta-genivi-dev/poky/conf/layer.conf, scripts/ci-build.sh, scripts/git-submodule-bump
14.1.x-sumo is ahead of master currently but it is also our latest tagged release, merge it back so that any further work on master is based on the latest release.
The pull-request is coming from "master" because we did a `git merge 14.1.x-sumo` on master ahead of creating this PR, this is to avoid running a `git rebase` because there are changes in master that do not exist in `14.1.x-sumo`
=>  reflect latest tagged release on master v2

README.md, gdp-src-build/conf/templates/r-car-h3-salvator-x.local.conf, gdp-src-build/conf/templates/r-car-m3-salvator-x.local.conf, gdp-src-build/conf/templates/renesas-rcar-gen3.local.inc, meta-genivi-dev/meta-genivi-dev/recipes-extended/cannelloni/cannelloni.bb
Sending this as PR to check the content.  Commits needed to be cherry picked separately since master has moved ahead to sumo.  These commits were proposed to master before that, so the intention should be that they apply also for rocko.  Just double-checking with @slawr and getting a build test on this first.
=> Salvator-x fixes to rocko maintenance branch

scripts/ci-build.sh
A minor thing.  Read commit msg.
=> ci-build: Allow override some parts of STANDARD_RELEASE_BUILD

meta-genivi-dev/meta-genivi-dev/recipes-cdl/cdl-concept-demo/cdl-concept-demo.bb
[GDP-812] cdl-concept-demo-1.0-r0 do_package_qa: QA Issue.
Found lib in wrong location
Signed-off-by: Mirza Krak <mirza.krak@northern.tech>
=> cdl-concept-demo: silence 'libdir' warning
